apiVersion: v1
kind: Secret
metadata:
  name: hr-db-credentials
  namespace: hr-backend
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "5432"
  DB_NAME: "demodb"
  DB_USER: "adminuser"
  DB_PASSWORD: "${DB_PASSWORD}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-system-config
  namespace: hr-backend
data:
  POMERIUM_JWKS_URL: "https://${POMERIUM_PRIVATE_IP}/.well-known/pomerium/jwks.json"
